"""initial schema

Revision ID: 89d305be3a7e
Revises:
Create Date: 2025-12-11 19:02:43.386601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "89d305be3a7e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "viewer", name="user_role"),
            server_default=sa.text("'viewer'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("idx_admin_role", "admin_users", ["role"], unique=False)
    op.create_table(
        "alert_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "Normal", "Minor", "Major", "Critical", name="alert_severity"
            ),
            nullable=True,
        ),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("alert_text", sa.Text(), nullable=True),
        sa.Column("counter", sa.Integer(), nullable=True),
        sa.Column("stacktrace", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "archived_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alert_history_server",
        "alert_history",
        ["server_id"],
        unique=False,
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_type", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("remote_addr", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_created", "audit_logs", ["created_at"], unique=False
    )
    op.create_table(
        "servers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("cgm_version", sa.Text(), nullable=True),
        sa.Column("admin_version", sa.Text(), nullable=True),
        sa.Column("last_update", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "last_status",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_servers_last_update", "servers", ["last_update"], unique=False
    )
    op.create_index(
        "idx_servers_region", "servers", ["region_id"], unique=False
    )
    op.create_table(
        "agent_keys",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_agent_keys_server", "agent_keys", ["server_id"], unique=False
    )
    op.create_index(
        "uq_agent_keys_keyhash", "agent_keys", ["key_hash"], unique=True
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "Normal", "Minor", "Major", "Critical", name="alert_severity"
            ),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("alert_text", sa.Text(), nullable=False),
        sa.Column(
            "counter",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("stacktrace", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alerts_server_active",
        "alerts",
        ["server_id", "active"],
        unique=False,
    )
    op.create_index(
        "idx_alerts_severity", "alerts", ["severity"], unique=False
    )
    op.create_table(
        "command_queue",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("DELETE_ALERT", "CUSTOM", name="command_type"),
            nullable=False,
        ),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("executed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "sent", "done", "failed", name="command_status"
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column(
            "attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("ttl_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_commands_server_status",
        "command_queue",
        ["server_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_commands_status_created",
        "command_queue",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "command_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("command_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("success", "failed", name="result_status"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["command_id"], ["command_queue.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_command_results_command",
        "command_results",
        ["command_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_command_results_command", table_name="command_results")
    op.drop_table("command_results")
    op.drop_index("idx_commands_status_created", table_name="command_queue")
    op.drop_index("idx_commands_server_status", table_name="command_queue")
    op.drop_table("command_queue")
    op.drop_index("idx_alerts_severity", table_name="alerts")
    op.drop_index("idx_alerts_server_active", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("uq_agent_keys_keyhash", table_name="agent_keys")
    op.drop_index("idx_agent_keys_server", table_name="agent_keys")
    op.drop_table("agent_keys")
    op.drop_index("idx_servers_region", table_name="servers")
    op.drop_index("idx_servers_last_update", table_name="servers")
    op.drop_table("servers")
    op.drop_index("idx_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("regions")
    op.drop_index("idx_alert_history_server", table_name="alert_history")
    op.drop_table("alert_history")
    op.drop_index("idx_admin_role", table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
